### ISSUE TITLE
Fetching Twitter's User & their friends details

### ISSUE THREAD

**Issue by SilambarasanRaman** [aaronksaunders/test_social#4]
Hi aaronksaunders,
Thanks for the your social_plug.js. I integrated your social_plug.js into my app.and this module only offers the share message in twitter.

But i want fetch the logged in user's details like screen name,first name,last name,user_id and friend count,followers count using the below url ,
var url= 'https://api.twitter.com/oauth/access_token';

Also fetching friend's id's  by using the below api call
 api('https://api.twitter.com/1.1/friends/ids.json?cursor=-1&screen_name='+scrname,'GET','',function(friendsid){

I already fetched the above details using this twitter library files https://github.com/jpurcell/birdhouse .But now i am changing my app with commonJS .
So that i need a commonJS modules for fetch these details.

Can you please create social_plug.js for the above requirement or please clarify me whether your current  social_plug.js offer these details or not..?

**Comment by aaronksaunders** [comment]
Don't understand why u need a fix if you are using birdhouse

**Comment by SilambarasanRaman** [comment]
Hey Aaronksaunders,

Thanks for your reply..I dropped the usage of birdhouse..because that is
not the commonjs.

So that only I tried to use your code..and currently I coded for fetch the
details like friends id's.

Thanks for your time.

**Comment by aaronksaunders** [comment]
so you have resolved your issue?

**Comment by SilambarasanRaman** [comment]
Yes.

On Mon, May 19, 2014 at 1:58 AM, aaronksaunders notifications@github.comwrote:

> so you have resolved your issue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aaronksaunders/test_social/issues/4#issuecomment-43450612
> .

## 

Thanks & Regards,
- Simbu *
  -  Develop Scripts LLC*
